site_name: Europa 1400 Database
site_url: https://europa1400-database.github.io/
site_description: ""
site_author: "Europa 1400 Community"
copyright: "Copyright &copy; 2024 Europa 1400 Community"
repo_url: https://github.com/europa1400-community/europa1400-database/
repo_name: europa1400-community/europa1400-database

theme:
  icon:
    repo: fontawesome/brands/github
  name: "material"
  palette:
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: "material/weather-sunny"
        name: Switch to light mode

    - scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: "material/weather-night"
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      name: View on GitHub
      link: https://github.com/europa1400-community/europa1400-database/
    - icon: fontawesome/brands/discord
      name: Join us on Discord
      link: https://discord.gg/jB9HYY8DpT

plugins:
  - search:
  - privacy:
  - gen-files:
      scripts:
        - scripts/generate_tables.py
        - scripts/generate_articles.py
        - scripts/generate_summary.py
  - literate-nav:
      nav_file: SUMMARY.md

markdown_extensions:
  - toc:
      permalink: "#"

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
